<a href="https://colab.research.google.com/github/132refrhyy/Muskan/blob/main/First_lab_ML_Muskan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#Question 01
def reverse_and_concatenate(A, B):
    reversed_A = A[::-1]
    result = reversed_A + B
    return result

string_A = "Hello"
string_B = " Python!"
final_string = reverse_and_concatenate(string_A, string_B)
print(final_string)

olleH Python!


In [7]:
#Question no 2
def find_highest_paid_female_worker(work_hours, pay_rate=20):
    hours_worked = 0
    female_worker = None

    for name, hours, gender in work_hours:
        if gender == 'F' and hours > hours_worked:
            hours_worked = hours
            female_worker = name

    if female_worker:
        payment = hours_worked * pay_rate
        return female_worker, payment
    else:
        return "No female workers found", 0

work_hours = [('Abby', 100, 'F'), ('Billy', 400, 'M'), ('Cassie', 800, 'F'), ('Maggi', 600, 'F'),
              ('Alex', 500, 'M'), ('Raj', 225, 'M'), ('Penny', 920, 'F'), ('Ben', 300, 'M')]

name, payment =find_highest_paid_female_worker(work_hours)
if name != "No female workers found":
    print(f"The female worker who worked the most hours is {name}.")
    print(f"She should be paid ${payment}.")
else:
    print(name)

The female worker who worked the most hours is Penny.
She should be paid $18400.


In [9]:
#Question no 3
import numpy as np
matrix = np.tile([[1,2],[2,2]],(5,2))
print(matrix)

[[1 2 1 2]
 [2 2 2 2]
 [1 2 1 2]
 [2 2 2 2]
 [1 2 1 2]
 [2 2 2 2]
 [1 2 1 2]
 [2 2 2 2]
 [1 2 1 2]
 [2 2 2 2]]


In [10]:
import numpy as np
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
if mat1.shape[1] == mat2.shape[0]:
  dot_product = np.dot(mat1 , mat2)
  print("dot product result :")
  print(dot_product)
else:
  print("matrix dimensions are not compatible for dot product")


dot product result :
[[19 22]
 [43 50]]
